"""HiQCache: quantized hierarchical KV cache for SGLang HiCache."""

from hiqcache.codec import (
    AMAX_FLOOR,
    QUANT_MAX,
    SCALE_FLOOR,
    ErrorStats,
    compute_scales,
    decode_records,
    dequantize_rows,
    encode_decode,
    encode_records,
    encode_rows,
    error_stats,
    pack_records,
    quantize_rows,
    unpack_records,
    verified_error_bound,
)
from hiqcache.layout import (
    ALIGNMENT_BYTES,
    BF16_ITEMSIZE,
    DEFAULT_PADDING_BYTES,
    DEFAULT_PAYLOAD_BYTES,
    DEFAULT_SCALE_BYTES,
    KVCACHE_K,
    KVCACHE_V,
    QWEN3_8B_HEAD_DIM,
    QWEN3_8B_KV_HEADS,
    QWEN3_8B_LAYER_NUM,
    V1_LAYOUT,
    RecordLayout,
    describe_compression,
    iter_region_spans,
    qwen3_8b_compression,
    qwen3_8b_layout_check,
)

__version__ = "0.1.0"

__all__ = [
    "ALIGNMENT_BYTES",
    "AMAX_FLOOR",
    "BF16_ITEMSIZE",
    "DEFAULT_PADDING_BYTES",
    "DEFAULT_PAYLOAD_BYTES",
    "DEFAULT_SCALE_BYTES",
    "ErrorStats",
    "KVCACHE_K",
    "KVCACHE_V",
    "QUANT_MAX",
    "QWEN3_8B_HEAD_DIM",
    "QWEN3_8B_KV_HEADS",
    "QWEN3_8B_LAYER_NUM",
    "RecordLayout",
    "SCALE_FLOOR",
    "V1_LAYOUT",
    "compute_scales",
    "decode_records",
    "dequantize_rows",
    "describe_compression",
    "encode_decode",
    "encode_records",
    "encode_rows",
    "error_stats",
    "iter_region_spans",
    "pack_records",
    "qwen3_8b_compression",
    "qwen3_8b_layout_check",
    "quantize_rows",
    "unpack_records",
    "verified_error_bound",
]
